import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer/Footer";

import { Toaster } from "react-hot-toast";




const poppins = Poppins({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  
});



export const metadata = {
  title: "SunAura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${poppins.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" />
        
        <Navbar></Navbar>
        
        
      
        <main className="flex-1 ">
          {children}
        </main>
        
        <Footer></Footer>

        
        
        </body>
    </html>
  );
}
